### ISSUE TITLE
Temporary file not being recreated after deletion

### ISSUE THREAD

**Issue by benjibrown** [spenkk/rapiddns-extractor#2]
If you run the tool, the file `domains-temp.txt` is modified and then deleted however it is not recreated upon the start of the program so if you were to run it more than twice you'd have to manually create the temporary file. This is a pretty simple fix, just create the file at the start before you need to access that file.

**Comment by spenkk** [comment]
Hi @benjibrown! 

The script is creating a file at the start with the following code `with open ('domains-temp.txt', 'a') as temp:`, later accessed with `for line in open('domains-temp.txt', 'r'):` and deleted at the end with `os.remove('domains-temp.txt')`. 

I'm sorry but I'm not sure I understand your issue since the script is working as it should on my side.

**Comment by spenkk** [comment]
Sorry since I closed it accidentally. Let me know if the above explanation solves your issue.

**Comment by 7ud** [comment]
Hmm weird, some reason it doesn't create it for me bit after running it on a different machine it does seem to work. My bad :)
